In [ ]:
import pandas as pd
import sklearn as sk
import numpy as np
import scipy as sp


In [ ]:
#Importing dataset
car_train=pd.read_csv("/content/sample_data/train.csv")
car_test=pd.read_csv("/content/sample_data/test.csv")
car_test.shape

(9065, 23)

In [ ]:
from sklearn import tree

var=list(car_train.columns[1:22])
c=car_train[var]
d=car_train['Fatal']


In [ ]:
c.shape

(15109, 21)

In [ ]:
d

0        1
1        1
2        1
3        1
4        1
        ..
15104    1
15105    1
15106    1
15107    1
15108    1
Name: Fatal, Length: 15109, dtype: int64

In [ ]:
###buildng Decision tree on the training data ####
clf = tree.DecisionTreeClassifier()
clf.fit(c,d)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
#####predicting on test data ####
tree_predict=clf.predict(car_test[var])


In [ ]:
from sklearn.metrics import confusion_matrix###for using confusion matrix###
cm1 = confusion_matrix(car_test[['Fatal']],tree_predict)
print(cm1)


[[3232  660]
 [ 716 4457]]


In [ ]:
#####from confusion matrix calculate accuracy
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
accuracy_tree


0.8482073910645339

In [ ]:
####Building Random Forest Model
from sklearn.ensemble import RandomForestClassifier
#forest=RandomForestClassifier(n_estimators=10,  min_samples_split=2, min_samples_leaf=1)
forest=RandomForestClassifier(n_estimators=50, max_features= 5)
     #max_features if Auto , then it takes Sq root of features

forest.fit(c,d)

forestpredict_test=forest.predict(car_test[var])
e=car_test['Fatal']


In [ ]:
###check the accuracy on test data
from sklearn.metrics import confusion_matrix###for using confusion matrix###
cm2 = confusion_matrix(car_test[['Fatal']],forestpredict_test)
print(cm2)
total2=sum(sum(cm2))


[[3376  516]
 [ 290 4883]]


In [ ]:
#####from confusion matrix calculate accuracy
accuracy_forest=(cm2[0,0]+cm2[1,1])/total2
accuracy_forest


0.9110865968008826

In [ ]:
#Boosting
##################################################################
#################LAB: Boosting

#importing the datasets
menu_train=pd.read_csv("/content/sample_data/Ecom_train.csv")
menu_test=pd.read_csv("/content/sample_data/Ecom_test.csv")


lab=list(menu_train.columns[1:101])
g=menu_train[lab]
h=menu_train['Category']


In [ ]:
menu_train.head()

id  spec1  spec2  spec3  spec4  ...  spec97  spec98  spec99  spec100  Category
0   1      1      0      0      0  ...      12       0       0        0   Mobiles
1   2      0      0      0      0  ...       1       0       0        0   Mobiles
2   3      0      0      0      0  ...       9       0       0        0   Mobiles
3   4      1      0      0      1  ...      21       0       0        0   Mobiles
4   5      0      0      0      0  ...      12       0       0        0   Mobiles

[5 rows x 102 columns]

In [ ]:
menu_train['Category'].value_counts()

Tablets          13079
Personal_Care    11452
Appliances        6863
Laptops           6466
Camara            3964
Accessories       2341
Ipod              2217
TV                2182
Mobiles           1558
Name: Category, dtype: int64

In [ ]:
###buildng Decision tree on the training data ####
from sklearn import tree
tree = tree.DecisionTreeClassifier()
tree.fit(g,h)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
#####predicting on test data ####
tree_predict=tree.predict(menu_test[lab])

from sklearn.metrics import confusion_matrix###for using confusion matrix###
cm1 = confusion_matrix(menu_test['Category'],tree_predict)
print(cm1)


[[ 252   42   12    5   53   22   48   16   48]
 [  45 1290   68    4   30   62   75    7   20]
 [  19   65  715    3   15   77   49    3   45]
 [   3    3    3  483    7    7    0    4   12]
 [  52   22   10    3  731    5   16   93  606]
 [  24   64   71    1   13  141   38    1   18]
 [  58   65   54    1   17   28 2415   15   30]
 [  19    6    1    1  100    4   30  199  149]
 [  48   37   30   12  615   14   30  140 2117]]


In [ ]:
## From Confusion Matrix calculate Accuracy
import sklearn.metrics as smetrics
smetrics.accuracy_score(menu_test['Category'],tree_predict)

0.7096801633208575

In [ ]:
##Gradient BOOSTING ##

###Building a gradient boosting clssifier ###
from sklearn import ensemble
from sklearn.ensemble import GradientBoostingClassifier
boost=GradientBoostingClassifier(loss='deviance',
                                 learning_rate=0.1,
                                 n_estimators=100, #Number of iterations
                                 min_samples_leaf=5,
                                 max_depth=3,
                                 verbose=1)

##calculating the time while fitting the Gradient boosting classifier
import datetime
start_time = datetime.datetime.now()
##fitting the gradient boost classifier
boost.fit(g,h)
end_time = datetime.datetime.now()
print(end_time-start_time)


      Iter       Train Loss   Remaining Time 
         1       83601.3278            3.70m
         2       76455.1290            3.67m
         3       71197.6703            3.62m
         4       66948.0468            3.58m
         5       63463.2613            3.54m
         6       60494.9142            3.51m
         7       57994.3798            3.48m
         8       55875.3214            3.44m
         9       53866.0839            3.40m
        10       52096.2352            3.37m
        20       41873.9097            3.00m
        30       37026.0952            2.62m
        40       34376.7404            2.25m
        50       32560.6629            1.88m
        60       31255.4565            1.51m
        70       30161.3067            1.13m
        80       29313.5813           45.09s
        90       28575.6133           22.53s
       100       27917.1192            0.00s
0:03:45.458981


In [ ]:


###predicting Gradient boosting model on the test Data
boost_predict=boost.predict(menu_test[lab])

from sklearn.metrics import confusion_matrix ## for using confusion Matrix
cm2 = confusion_matrix(menu_test['Category'],boost_predict)
print(cm2)

#Accuracy
import sklearn.metrics as smetrics
smetrics.accuracy_score(menu_test['Category'], boost_predict)


# from sklearn.metrics import f1_score
# f1_score(menu_test['Category'], boost_predict, average='micro')






[[ 306   29    0    1   26   10   40    7   79]
 [  14 1457   31    1    3   20   47    0   28]
 [   3   39  850    2    0   25   41    0   31]
 [   0    1    0  500    1    0    0    1   19]
 [  22    5    6    0  678    0    2   23  802]
 [   7   73   80    0    5  146   32    0   28]
 [  37   35   34    1    2   11 2516    2   45]
 [   7    1    0    3   72    0   21  169  236]
 [  18    8    6    9  331    0    8   23 2640]]


0.787853011228309